BBNAPS1:
  type: APS
  master: false
  enabled: false
  slave_trig: 4m1
  address: 0
  seq_file: thing.h5
  delay: 0.0
  tx_channels:
    '12':
      phase_skew: 0
      amp_factor: 1
      '1':
        enabled: true
        offset: 0
        amplitude: 0.5
      '2':
        enabled: true
        offset: 0.02
        amplitude: 0.5
    '34':
      phase_skew: 0
      amp_factor: 1
      '3':
        enabled: true
        offset: 0
        amplitude: 0.5
      '4':
        enabled: true
        offset: 0.00
        amplitude: 0.5
  markers:
    1m1:
      delay: -5.0e-08
    2m1:
      delay: 0.0
    3m1:
      delay: 0.0
    4m1:
      delay: 0.0

Cav-APS2:
  type: APS2               # Used by QGL and Auspex. QGL assumes XXXPattern for the pattern generator
  enabled: true            # true or false, optional
  master: true             # true or false
  slave_trig:  12m4            # name of marker below, optional, i.e. 12m4. Used by QGL.
  address: 192.168.2.4                # IP address or hostname should be fine
  trigger_interval: 25e-6    # (s)
  trigger_source: Internal # Internal, External, Software, or System
  seq_file: test.h5        # optional sequence file
  tx_channels:             # All transmit channels
    '12':                  # Quadrature channel name (string)
      phase_skew: 0.0      # (deg) - Used by QGL
      amp_factor: 1.0      # Used by QGL
      delay: 0.0           # (s) - Used by QGL
      '1':
        enabled: true
        offset: 0.0
        amplitude: 1.0
      '2':
        enabled: true
        offset: 0.0
        amplitude: 1.0
  markers:
    12m1:
      delay: 0.0         # (s)
    12m2:
      delay: 0.0
    12m3:
      delay: 0.0
    12m4:
      delay: 0.0

Q-APS2:
  type: APS2               # Used by QGL and Auspex. QGL assumes XXXPattern for the pattern generator
  enabled: false           # true or false, optional
  master: false             # true or false
  slave_trig:  12m4            # name of marker below, optional, i.e. 12m4. Used by QGL.
  address: 192.168.2.5                # IP address or hostname should be fine
  trigger_interval: 25e-6    # (s)
  trigger_source: External # Internal, External, Software, or System
  seq_file: test.h5        # optional sequence file
  tx_channels:             # All transmit channels
    '12':                  # Quadrature channel name (string)
      phase_skew: 0.0      # (deg) - Used by QGL
      amp_factor: 1.0      # Used by QGL
      delay: 0.0           # (s) - Used by QGL
      '1':
        enabled: true
        offset: 0.0
        amplitude: 1.0
      '2':
        enabled: true
        offset: 0.0
        amplitude: 1.0
  markers:
    12m1:
      delay: 0.0         # (s)
    12m2:
      delay: 0.0
    12m3:
      delay: 0.0
    12m4:
      delay: 0.0

Alazar:
  type: AlazarATS9870
  enabled: True
  label: Alazar
  address: 1
  acquire_mode: digitizer
  bandwidth: Full
  clock_type: ref
  delay: 0
  record_length: 4096
  nbr_samples: 4096
  nbr_segments: 1
  nbr_waveforms: 1
  nbr_round_robins: 1000
  sampling_rate: 1e9
  trigger_coupling: DC
  trigger_level: 100
  trigger_slope: rising
  trigger_source: Ext
  vertical_coupling: AC
  vertical_offset: 0
  vertical_scale: .04

SynthHD:
  type: SynthHD
  address: COM5
