# Qubit configuration for the 21.1st century.
# Imports can be made using the !include keyword. e.g.
# instruments: !include instruments.yml

qubits:
  q1:
    measure:
      AWG: Cav-APS2 12
      trigger: Cav-APS2 12m1
      receiver: Stream-q1
      generator: SynthHD
      autodyne_freq: 10000000.0
      gate: Cav-APS2 12m2
      pulse_params:
        amp: 1.0
        cutoff: 2.0
        length: 5.0e-06
        shape_fun: tanh
        sigma: 1.0e-09
    control:
      AWG: Q-APS2 12
      generator: SynthHD
      gate: Q-APS2 12m1
      pulseParams:
        cutoff: 2.0
        length: 7.0e-08
        pi2Amp: 0.4
        piAmp: 0.8
        shape_fun: drag
        drag_scaling: 0.0
        sigma: 5.0e-09

instruments: !include instruments.yml
filters: !include filters.yml
